version: 2

sphinx:
    builder: html
    configuration: doc/source/conf.py

python:
    version: 3.7
    install:
        - requirements: docs/requirements.txt
        - method: pip
          path: .
          extra_requireemnts:
              - docs
    system_packages: true
